// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRlv_9CsbQOBesZdePpwlMr0a0XpM9DyE',
    appId: '1:762621121311:web:ae6a75ec07227f838cd62a',
    messagingSenderId: '762621121311',
    projectId: 'poker-app-2',
    authDomain: 'poker-app-2.firebaseapp.com',
    storageBucket: 'poker-app-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjIiLIT5XSwbT2MKXk3NWl79H5_HjJMCU',
    appId: '1:762621121311:android:81d80ff92f83835d8cd62a',
    messagingSenderId: '762621121311',
    projectId: 'poker-app-2',
    storageBucket: 'poker-app-2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2UFQl_RvwU3O0JS5WMXmyblLOcXTFMG4',
    appId: '1:762621121311:ios:66d15d3b23df45e08cd62a',
    messagingSenderId: '762621121311',
    projectId: 'poker-app-2',
    storageBucket: 'poker-app-2.firebasestorage.app',
    iosBundleId: 'com.example.pokerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRlv_9CsbQOBesZdePpwlMr0a0XpM9DyE',
    appId: '1:762621121311:web:1e28cebe5ec3e52f8cd62a',
    messagingSenderId: '762621121311',
    projectId: 'poker-app-2',
    authDomain: 'poker-app-2.firebaseapp.com',
    storageBucket: 'poker-app-2.firebasestorage.app',
  );
}
